"""Century 21 Cayman (century21cayman.com) scraper.

Why curl got 403: the site sits behind CloudFront + AWS WAF.  Requests with a
non-browser User-Agent (e.g. curl's default) are refused outright, and the WAF
also has an aggressive rate rule: after roughly 8 page requests within a
couple of minutes (even at 1 req/sec) the whole site returns
"403 ... Request blocked. Generated by cloudfront" for this IP for a while.
The HTML pages also load an AWS WAF JS challenge script.  We do NOT try to get
around any of that: requests go out slowly (see EXTRA_DELAY), and on the
first 403 we stop.  If nothing was fetched we raise RuntimeError.

How the data is served
----------------------
Server-rendered WordPress/"UDX" search pages, 12 cards per page:

    /en/s/for-sale/single-family-homes        (page 1)
    /en/s/for-sale/single-family-homes/2      (page 2, ...)
    /en/s/for-sale/condos-apartments[/N]
    /en/s/for-sale/vacant-land[/N]

robots.txt disallows /en/s/ except for these explicitly allowed category
paths, and disallows the sort-order URLs (/hga/, /lga/, ...) that the site's
own pager links to, so we page with the plain `/<category>/<N>` form, which
the server also accepts.  The /en/s/residential/.../featured page is not
allowed by robots.txt, so it is not used.

Each card gives: price with currency (US$ / CI$), title, district, category,
beds, baths, view, lot acres, ribbon status, photo.  The CIREBA MLS number is
only on detail pages (/en/d/..., allowed by robots.txt); fetching them is
off by default (MLS_DETAILS = 0) because each one counts against the WAF rate
limit.  Set MLS_DETAILS (max 40) to fill `mls` for the first N listings.

This is the full CIREBA MLS feed (LDX/IDX: detail pages say "CIREBA MLS LDX
feed courtesy of <other brokerage>"), not only Century 21's own listings; the
site does not separate its own listings in any robots-allowed URL.
"""
from __future__ import annotations

import re
import time
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup

from scraper.common import Listing, get, num, parse_price, norm_type, HOME, CONDO, LAND

SOURCE = "Century 21"
BASE = "https://century21cayman.com"
CATEGORIES = [("single-family-homes", HOME), ("condos-apartments", CONDO), ("vacant-land", LAND)]
EXTRA_DELAY = 4.0     # seconds on top of common.get()'s 1 s throttle (WAF rate rule)
MLS_DETAILS = 0       # detail pages to fetch for MLS numbers (0 = off, max 40)
SQFT_PER_ACRE = 43560.0


class _Blocked(Exception):
    pass


def _get(url: str) -> str:
    time.sleep(EXTRA_DELAY)
    try:
        r = get(url, headers={"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"})
    except requests.HTTPError as e:
        if e.response is not None and e.response.status_code in (403, 405, 429):
            raise _Blocked(e.response.status_code) from e
        raise
    if "awswaf" in r.url or ("challenge-container" in r.text and "card-listing" not in r.text):
        raise _Blocked("challenge")
    return r.text


def _count(text: str) -> float | None:
    """'14½' -> 14.5, '5½+' -> 5.5, '29+' -> 29."""
    t = (text or "").strip()
    v = num(t)
    if v is None:
        return 0.5 if "½" in t else None
    return v + (0.5 if "½" in t else 0)


def _location(text: str) -> str:
    t = re.sub(r"\s*\(Grand Cayman\)\s*$", "", (text or "").strip())
    return t.replace(" / ", "/")


def _parse_cards(html: str, default_type: str) -> list[Listing]:
    soup = BeautifulSoup(html, "lxml")
    out: list[Listing] = []
    for art in soup.select("article.card-listing"):
        try:
            body = art.select_one("a.card-body[href]") or art.select_one("a[href*='/en/d/']")
            if not body:
                continue
            url = urljoin(BASE, body["href"].split("?")[0])
            hdr = art.select_one(".card-header")
            price, cur = parse_price(hdr.get_text(" ", strip=True) if hdr else None)
            if not price:
                continue
            spans = [s.get_text(" ", strip=True) for s in body.select("h2 span")]
            title = spans[0] if spans else (art.get("data-ad-title") or "")
            loc = _location(spans[1]) if len(spans) > 1 else ""
            category = spans[2] if len(spans) > 2 else ""
            if re.search(r"commercial|business|rent", category, re.I):
                continue
            ptype = default_type
            if category:
                t = norm_type(category)
                if "single family" in category.lower():
                    t = HOME
                ptype = t if t != "other" else default_type

            beds = baths = acres = None
            info = body.select_one("span.fs-80")
            if info:
                parts = [p.strip() for p in info.get_text(" ", strip=True).split("·")]
                icons = [u.get("href", "") for u in info.select("use")]
                idx = 0
                for icon in icons:
                    if idx >= len(parts):
                        break
                    if "fa-bed" in icon:
                        beds = _count(parts[idx]); idx += 1
                    elif "fa-bath" in icon:
                        baths = _count(parts[idx]); idx += 1
                for p in parts:
                    m = re.search(r"([\d.,]+)\s*Acres?", p, re.I)
                    if m:
                        acres = num(m.group(1))
            sqft = round(acres * SQFT_PER_ACRE) if (ptype == LAND and acres) else None

            rib = art.select_one(".ribbon")
            status = rib.get_text(" ", strip=True) if rib else ""
            if re.search(r"\bsold\b|leased|rented", status, re.I):
                continue
            if re.search(r"under (contract|offer)|pending", status, re.I):
                status = "Under Offer"
            else:
                status = "For Sale"

            img = art.select_one("img.thumb") or art.select_one("img[src]")
            image = urljoin(BASE, img["src"].split("?")[0]) if img and img.get("src") else ""

            out.append(Listing(
                source=SOURCE, url=url, title=title, price=price, currency=cur,
                ptype=ptype, location=loc,
                beds=None if ptype == LAND else beds,
                baths=None if ptype == LAND else baths,
                sqft=sqft, acres=acres, image=image, status=status,
            ))
        except Exception:
            continue
    return out


def _mls_from_detail(html: str) -> str:
    m = re.search(r"CIREBA MLS:\s*(\d+)", html) or re.search(r"<b>CIREBA</b>\s*(\d+)", html)
    return m.group(1) if m else ""


def fetch(max_pages: int = 5) -> list[Listing]:
    """Full CIREBA feed as shown on century21cayman.com, for sale only.
    `max_pages` is the page cap per category (homes, condos, land); 12 per page."""
    results: list[Listing] = []
    seen: set[str] = set()
    blocked = None

    for slug, ptype in CATEGORIES:
        if blocked:
            break
        for page in range(1, max_pages + 1):
            url = f"{BASE}/en/s/for-sale/{slug}" + (f"/{page}" if page > 1 else "")
            try:
                html = _get(url)
            except _Blocked as e:
                blocked = e
                break
            except Exception:
                break
            cards = _parse_cards(html, ptype)
            new = [c for c in cards if c.url not in seen]
            for c in new:
                seen.add(c.url)
            results.extend(new)
            if not cards or not new:
                break
            # Last page: pager has no link to page+1.
            if not re.search(rf'/{re.escape(slug)}/(?:[a-z]ga/)?{page + 1}"', html):
                break

    if blocked and not results:
        raise RuntimeError(
            "Century 21 Cayman (century21cayman.com) blocks automated access "
            f"(HTTP 403 from CloudFront/AWS WAF: {blocked}). Not retrying; "
            "the block is rate-based and usually lifts after some minutes.")

    if not blocked:
        for lst in results[:min(MLS_DETAILS, 40)]:
            try:
                lst.mls = _mls_from_detail(_get(lst.url))
            except _Blocked:
                break
            except Exception:
                continue
    return results
